name: Zizmor

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['**']

permissions: {}

jobs:
  zizmor:
    name: zizmor
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: false

      - name: Run zizmor
        run: uvx zizmor@1.23.1 .github/workflows -v -p --min-severity=medium
